{"name": "test_login_uninvalid_username[data0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '此账号没有经过授权，请联系管理员!' == ''\n  + 此账号没有经过授权，请联系管理员!", "trace": "self = <tests.test_login.TestLogin object at 0x0000000004C18DA0>, data = {'expected': '此账号没有经过授权，请联系管理员!', 'pwd': '1', 'username': '18585436789'}\nbrowser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"804f2edec9a5fba25b73b3e4c7ba4677\")>\n\n    @pytest.mark.parametrize('data',login_data_uninvalid)\n    def test_login_uninvalid_username(self,data,browser):\n        expected=data['expected']\n        actual=LoginPage(browser).get().login_fail(data['username'],data['pwd']).get_invalid_msg()\n>       assert expected==actual\nE       AssertionError: assert '此账号没有经过授权，请联系管理员!' == ''\nE         + 此账号没有经过授权，请联系管理员!\n\ntests\\test_login.py:16: AssertionError"}, "parameters": [{"name": "data", "value": "{'username': '18585436789', 'pwd': '1', 'expected': '此账号没有经过授权，请联系管理员!'}"}], "start": 1612277905191, "stop": 1612277905707, "uuid": "1435d917-7bbf-4c29-9afd-44b0daaa730d", "historyId": "fa5fd66b63c2bcd93bb5f71880ea55e5", "testCaseId": "fc3697ccfb19cd021c9297d4c4fc5f65", "fullName": "tests.test_login.TestLogin#test_login_uninvalid_username", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "J8WB1KTCQOB0HW1"}, {"name": "thread", "value": "12296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}